name: rakesh_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.0.0+2
  dotted_border: 2.0.0+3
  dio: ^5.4.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansRegular.ttf
          weight: 400
